background_opacity 0.98

background #262626
foreground #71A66F
cursor #BF1F1F

color0  #71A66F
color1  #D98825
color2  #BF1F1F
color3  #498C8C
color4  #71A66F
color5  #D98825
color6  #BF1F1F
color7  #498C8C
color8  #71A66F
color9  #D98825
color10  #BF1F1F
color11  #498C8C
color12  #71A66F
color13  #D98825
color14  #BF1F1F
color15  #498C8C

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard


